### ISSUE TITLE
Test case <WINNF.FT.C.MES.4> is getting failed with provided JSON and CSV file 

### ISSUE THREAD

**Issue by pawan25062** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#64] opened 2017-11-17 12:17 UTC
Hi,
Test case <WINNF.FT.C.MES.4: Heartbeat Response contains measReportConfig> is getting failed with provided JSON and CSV file, even CBSD is sending measurement reports in HB request.
Used following CSV and JSON files from master branch:
WINNF.FT.C.MES.4_measConf_in_HB.csv 
jsonFileName
HBT_registration_Cbsd1.json
HBT_spectrumInquiry_Cbsd.json
HBT_grant_Cbsd.json
MES_heartbeat_GrantedState_MeasConf.json
MES_heartbeat_AuthState_MeasRep1.json
MES_heartbeat_AuthState_MeasRep1.json
MES_heartbeat_AuthState_MeasRep1.json
MES_heartbeat_AuthState_MeasRep1.json
MES_heartbeat_AuthState_MeasRep1.json
MES_heartbeat_AuthState_MeasRep1.json

Please find attached log file for this test case.
[WINNF.FT.C.MES.4_measConf_in_HB_2017-11-17T11.54.27Z.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1482232/WINNF.FT.C.MES.4_measConf_in_HB_2017-11-17T11.54.27Z.zip)

**Comment by ericzh31ericsson** [comment] 2017-11-17 14:01
Because your CBSD only sent one measurement report in HB request with Authorized state, there was no more after that, then test was failed due to 5 no report HB request. Mock-SAS expected at least one more measurement report during this time.

**Comment by cwilliams-ericsson** [comment] 2017-11-17 15:49
I see the problem.  Will fix in upcoming clean-up of HBT & MES test cases.

**Comment by pawan25062** [comment] 2017-12-06 13:00
hi,
we have tried same test case with latest master branch and observed test case failed with mismatch in HB interval:
2017-12-06T12:46:39.358Z - INFO - heartbeat request from CBRS  : {
    "heartbeatRequest": [
        {
            "cbsdId": "S9GQ710US01Mock-SAS401629000040", 
            "grantId": "528509500", 
            "operationState": "AUTHORIZED"
        }
    ]
}
2017-12-06T12:46:39.358Z - INFO - The time interval between two heartbeat request messages is 120.011
2017-12-06T12:46:39.358Z - INFO - the server shot down because :  ERROR - the duration between the heartbeats are more then expected from json file
2017-12-06T12:46:40.232Z - INFO - The final result of the test : WINNF.FT.C.MES.4_measConf_in_HB is - FAIL

log file is attached here for reference.
[WINNF.FT.C.MES.4_measConf_in_HB_2017-12-06T12.36.11Z.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1535198/WINNF.FT.C.MES.4_measConf_in_HB_2017-12-06T12.36.11Z.zip)

**Comment by cwilliams-ericsson** [comment] 2017-12-15 21:33
Seems to be a duplicate of Issue #68 ?

**Closed as completed** 2018-03-12 13:17 UTC
Labels: Fixed - Validate
